### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by mattbailey0** [opengovfoundation/madison#893]
Currently, Madison users who are on Internet Explorer 9 and below experience near total failure of the site to load, due to Angular's lack of support.  While it may not be possible to provide a full experience for these users, they should at least get a basic error page that lets them know that their browser isn't supported.  

It would also be useful to be able to configure the text for that screen via a .md file or the administrative GUI so that site owners can provide some basic instruction for how else to get involved/provide feedback on legislation.

**Comment by DCOPENGOV** [comment]
This is error message: 
![untitled](https://cloud.githubusercontent.com/assets/6886322/13610182/76bff58c-e52a-11e5-87ad-580ec4f59a61.png)

**Comment by krues8dr** [comment]
We spent a lot of time on IE9 support over a year ago, but there's been a major redesign since.  We still would like to keep IE9 support for a while longer at least, so we'll dig in on this right away.

**Comment by krues8dr** [comment]
Getting there... 
![screen shot 2016-03-08 at 2 12 12 pm](https://cloud.githubusercontent.com/assets/127904/13612906/cd26c560-e537-11e5-9677-889ae6c936ab.jpg)

**Comment by krues8dr** [comment]
Ok, with that patch above, at least things load.  Kinda.  Here's the TODO list moving forward:

* [ ] [Fix styles](https://github.com/opengovfoundation/madison/issues/896)
* [ ] [Check & Fix Links](https://github.com/opengovfoundation/madison/issues/897)
* [ ] [Check & Fix  Annotations](https://github.com/opengovfoundation/madison/issues/898)
* [ ] [Check & Fix  Admin](https://github.com/opengovfoundation/madison/issues/899)

**Comment by sethetter** [comment]
* [ ] Also, #901.

**Comment by krues8dr** [comment]
Aside from punting on #901, this should be just about done.  I'll open a PR for this work now.

**Comment by sethetter** [comment]
@krues8dr I'm still seeing some link issues now actually. If you try to visit a link without a `/#/` in the beginning, it just jumps to the homepage instead of going to the actual link. I thought this was working but apparently not.

**Comment by krues8dr** [comment]
I may have broken this with my previous attempted fix for urls.  I'll have another look.

**Comment by krues8dr** [comment]
@sethetter that _should_ fix it.

**Comment by sethetter** [comment]
@krues8dr yep! That did it.

Weird thing happening with email verification links though. The verify works, but when it re-applies the route with the `/#/`, it tries to *re*-verify, and says the link is invalid.

Digging in now.

**Comment by sethetter** [comment]
@krues8dr verify tokens working properly now. Anything else on your list?
